name: Set Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to set"
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  set-version:
    name: Set Version
    permissions:
      contents: write
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: lts/*
          check-latest: true

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: latest

      - name: Set package version
        run: pnpm version --no-git-tag-version --allow-same-version ${INPUTS_VERSION}
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name: Add release to metainfo
        run: |
          if ! grep -q "<release version=\"${INPUTS_VERSION}\"" com.soulfiremc.soulfire.metainfo.xml; then
            sed -i "/<releases>/a\\
              <release version=\"${INPUTS_VERSION}\" date=\"$(date +"%Y-%m-%d")\">\\
                <url type=\"details\">https://github.com/soulfiremc-com/SoulFireClient/releases/tag/${INPUTS_VERSION}</url>\\
              </release>" com.soulfiremc.soulfire.metainfo.xml
            echo "Added release ${INPUTS_VERSION} to metainfo file"
          else
            echo "Release version ${INPUTS_VERSION} already exists in metainfo file, skipping addition"
          fi
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore(release): bump version to ${{ inputs.version }}"
