name: Set Server Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Server version to set'
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  set-server-version:
    name: Set Server Version

    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      - name: 'Shared: Checkout repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}

      - name: 'Set Server Version'
        run: |
          echo "${INPUTS_VERSION}" > soulfire-server-version.txt
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name: 'Commit Version'
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'chore(server): bump server version to ${{ inputs.version }}'
